config/routes.rb
# Rails.application.routes.draw do
#    For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
#
# resources :entries
#
# Prefix Verb   URI Pattern                 Controller#Action
#    entries GET    /entries(.:format)          entries#index
#            POST   /entries(.:format)          entries#create
#  new_entry GET    /entries/new(.:format)      entries#new
# edit_entry GET    /entries/:id/edit(.:format) entries#edit
#     entry GET    /entries/:id(.:format)      entries#show
#            PATCH  /entries/:id(.:format)      entries#update
#            PUT    /entries/:id(.:format)      entries#update
#            DELETE /entries/:id(.:format)      entries#destroy
#
#
#
# end
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :entries
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController

  def index
    @entries = Entry.all.sort
  end

  def show
    @entry = Entry.find(params[:id])
  end

  

  def new
    @entry = Entry.new
  end

  def create
    @entry = Entry.new
    @entry.word = params[:entry][:word]
    @entry.definition = params[:entry][:definition]
    @entry.language = params[:entry][:language]

    if @entry.save
      redirect_to entries_url
    else
      redirect_to new_entry_url
    end
  end

  def edit
    @entry = Entry.find(params[:id])
  end

  def update
    @entry = Entry.find(params[:id])
    @entry.word = params[:entry][:word]
    @entry.definition = params[:entry][:definition]
    @entry.language = params[:entry][:language]

    if @entry.save
      redirect_to entry_url(params[:id])
    else
      redirect_to edit_entry_url(params[:id])
    end
  end

  def destroy
    @entry = Entry.find(params[:id])
    @entry.destroy
    redirect_to entries_url
  end

end


# class EntriesController < ApplicationController
#
#   def index
# render :index
#   end
#
# def show
#   render :show
# end
#
# def new
#   render :new
#   end
#
#   def create
#     redirect_to entries_url
#   end
#
#   def edit
#     redirect_to entry_url(params[:id]
#    end
#
#
#      def destroy
#    render :index
#      end
#
# end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/enteries_helper.rb
module EnteriesHelper
end

app/views/entries/_entry_form.html.erb
<%= form_for entry do |f| %>

<h4><%= f.label :word %></h4>
<h4><%= f.text_field :word %></h4>

<h4><%= f.label :definition %></h4>
<h4><%= f.text_field :definition %></h4>

<h4><%= f.label :language %></h4>
<h4><%= f.text_field :language %></h4>

<h4><%= f.submit %></h4>

<% end %>

app/views/entries/edit.html.erb
<p> "the edit entry form will go here later!".</p>

<h1>Edit word</h1>

<%= link_to "Edit", entry_path(@entry) %>

<%= render "entry_form", entry: @entry %>

app/views/entries/index.html.erb
<h1>index entries page </h1>

<h2><%= link_to "Add a word", new_entry_path(@entry) %></h2>

  <% @entries.each do |entry| %>
    <h2><%= link_to entry.word.capitalize, entry_path(entry) %></h2> <br>
  <% end %>

app/views/entries/new.html.erb
<p> "the new entry form will go here later!".</p>

<h1>So you want a new word</h1>

<%= link_to "New", entries_path %>

<!-- as -->

<%= render "entry_form", entry: @entry %>

app/views/entries/show.html.erb
<p> Show page for entries</p>
<p>information for entry number<%= params[:id] %></p>

<h1><%= @entry.word.titleize %></h1>
<p>Definition: <%= @entry.definition.capitalize %></p> <br>
<h4>Language: <%= @entry.language.upcase %></h4> <br>

<%= link_to "Edit", edit_entry_path(@entry) %>
<%= link_to "Delete", entry_path(@entry), method: :delete, data: {confirm: "Delete '#{@entry.word}'?"} %>
<%= link_to "List", entries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dictionary</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>